CSJ Tower (tên pháp lý là DIC Star Apart’s Hotel) là dự án căn hộ khách sạn nằm trong khu phức hợp Cap Saint Jacques, tọa lạc ngay mặt tiền biển Bãi Sau, số 169 Thùy Vân, phường 8, thành phố Vũng Tàu, tỉnh Bà Rịa – Vũng Tàu
Dự án chung cư The Matrix One sẽ là sự khác biệt, khác biệt hoàn toàn so với phần còn lại. Không khí tươi, nguồn nước sạch, công viên và hồ cảnh quan rộng lớn, tầm nhìn trọn đường đua F1 đẳng cấp thế giới là lời khẳng định “vượt lên tất cả” về chất sống
Grandeur Palace có lợi thế đặc biệt về vị trí mà không phải tòa nhà văn phòng nào thuộc khu vực Ba Đình cũng có được. Sự kết hợp giữa yếu tố giao thông và hệ thống cơ sở hạ tầng, trang thiết bị hiện đại đã thu hút một lượng lớn khách thuê góp phần vào sự đa dạng của thị trường bất động sản Hà Nội.
Happy One Central là dự án căn hộ cao cấp tọa lạc vị trí trung tâm của Thành Phố Thủ Dầu Một. Dự án gồm 2 tòa tháp cao 40 tầng, đáp ứng hơn 1300 căn hộ cho những cư dân tương lai. Sau khi hoàn thành, Happy One Central sẽ trở thành một biểu tượng mới của Thành Phố Thủ Dầu Một.
FLC Quang Binh Beach & Golf Resort mang nguồn cảm hứng bất tận từ sắc xanh dương của biển hòa quyện cùng những thanh âm dào dạt, tràn sức sống nơi đại dương bao la.
The Sol City Thắng Lợi – Khu đô thị kiểu mẫu đạt tiêu chuẩn cao cấp có quy mô lớn bậc nhất Long An, khát vọng hướng tới các giá trị sống – giải trí cân bằng, trở về với tự nhiên, kiến tạo nên một không gian sống trọn vẹn, đáng mơ ước.. Với số lượng hơn 1300 sản phẩm là đất nền nhà phố, biệt thự,
Eurowindow River Park là khu phức hợp đẳng cấp, xây dựng theo phong cách kiến trúc hiện đại, bao gồm tổ hợp officetel, shophouse và khu căn hộ cao cấp.
CÔNG TY TNHH MÁY THIẾT BỊ VÀ XÂY DỰNG HÓA CHẤT  , tiền thân là Nhà máy Cơ khí hóa chất Thủ Đức, được thành lập từ năm 1976. Với trên 40 năm kinh nghiệm trong các lĩnh vực :Thiết kế, chế tạo, lắp đặt máy móc, thiết bị cho tất cả các ngành , Công ty đã là đối tác tin cậy của nhiều Doanh nghiệp trong và ngoài nước.
Novaworld Hồ Tràm Bình Châu tại Bà Rịa Vũng Tàu thuộc Quần thể giải trí nghỉ dưỡng đẳng cấp do Novaland Group phát triển, được ra mắt song song cùng với dự án Aqua City & Novaworld Phan Thiết tại Bình Thuận.
